### PR TITLE
fix: Default to magrittr pipe for R < 4.2

### PR DESCRIPTION
**Pull request by krlmlr**
Otherwise users end up with non-parseable code.

### CODE REVIEW

**Comment by krlmlr** [comment]
How do we handle the snapshot test failures? Skipping wouldn't be too bad, IMO.

**Comment by moodymudskipper** [comment]
Thanks, I think it's reasonable, another option would be to have `pipe = default_pipe()`. This would make it a bit more DRY, but we can revisit if we need to copy paste this more.

Ultimately we should be able to set the R and package versions we want to construct for as an option, so it will be something like: 

`if (getOption("constructive.Rversion", getRversion())  >= "4.2")` ...

**Comment by krlmlr** [comment]
To adapt the snapshot tests, we want `expect_pipe_snapshot()` that forwards to `expect_snapshot()` and uses the `transform` argument.

**Comment by krlmlr** [comment]
On it now, submitting PR soon.

**Pull request merged**
