### PR TITLE
Forward the dots in POSIXct to handle `max_atomic = 0`

### LINKED ISSUE #6: The output of `construct(a_tibble, max_atomic = 0)`  is not entirely correct for columns  of class "POSIXct"
``` r
df <- tibble::tibble(a = 1:2,
                     b = 2:3,
                     c = rep(as.POSIXct(Sys.time(), tz = "UTC"), 2))
df
#> # A tibble: 2 × 3
#>       a     b c                  
#>   <int> <int> <dttm>             
#> 1     1     2 2022-07-14 15:24:08
#> 2     2     3 2022-07-14 15:24:08
constructive::construct(df, max_atomic = 0)
#> tibble::tibble(
#>   a = integer(0),
#>   b = integer(0),
#>   c = as.POSIXct(c("2022-07-14 15:24:08.66721", "2022-07-14 15:24:08.66721")) |>
#>     structure(tzone = NULL),
#> )
```

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Can I try fix this and fill a PR?

### PR DESCRIPTION
**Pull request by andreranza**
Closes #6

### CODE REVIEW

**Comment by andreranza** [comment]
Not entirely sure 69771424606ec85aebab66f231547b6113d768bf is sufficient tough.

```
df <- tibble::tibble(a = 1:2,
                     b = 2:3,
                     c = rep(as.POSIXct(Sys.time(), tz = "UTC"), 2))

df
#> # A tibble: 2 × 3
#>       a     b c                  
#>   <int> <int> <dttm>             
#> 1     1     2 2022-07-14 16:24:50
#> 2     2     3 2022-07-14 16:24:50

constructive::construct(df, max_atomic = 0)
#> tibble::tibble(
#>   a = integer(0),
#>   b = integer(0),
#>   c = POSIXct(0) |>
#>     structure(tzone = NULL),
#> )
Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org/) (v2.0.1)
```

I doubt if the wanted output for column "c" in this case is:

* `POSIXct(0)`
* `as.POSIXct(0) |> structure(tzone = NULL, origin = NULL)`

I think the latter would be the wanted solution, since the former is not proper R code.

**Comment by andreranza** [comment]
Probably not elegant but it works and test do not fail.
```
df <- tibble::tibble(a = 1:2,
                     b = 2:3,
                     c = rep(as.POSIXct(Sys.time(), tz = "UTC"), 2))

df
#> # A tibble: 2 × 3
#>       a     b c                  
#>   <int> <int> <dttm>             
#> 1     1     2 2022-07-15 15:40:35
#> 2     2     3 2022-07-15 15:40:35

constructive::construct(df, max_atomic = 0)
#> tibble::tibble(
#>   a = integer(0),
#>   b = integer(0),
#>   c = POSIXct(0) |>
#>     structure(tzone = NULL),
#> )

tibble::tibble(
  a = integer(0),
  b = integer(0),
  c = as.POSIXct(numeric(0)) |>
    structure(tzone = NULL),
)
#> # A tibble: 0 × 3
#> # … with 3 variables: a <int>, b <int>, c <dttm>
```
Created on 2022-07-15 by the [reprex package](https://reprex.tidyverse.org/) (v2.0.1)

**Comment by andreranza** [comment]
What about `numeric(0)` -> `character(0)`? It might simplify the code even more, I guess.
```
tibble::tibble(
  a = integer(0),
  b = integer(0),
  c = as.POSIXct(character(0)) |>
    structure(tzone = NULL),
)
```

**Comment by moodymudskipper** [comment]
The way this package work is that we apply constructors depending on classes recusively and ultimately we always fall back on atomic methods, which are either the default methods or the numeric method. `max_atomic` is handled there so we shouldn't have exceptions upstream. The problem is that if the dots are not properly forwarded as is the case here, the default method called from the POSIXct method doesn't see `max_atomic`.

**Comment by moodymudskipper** [comment]
Also FYI the "structure(tzone = NULL)" part is not very pretty but I'll believe we'll encounter those only with timestamps build from `Sys.time()`. POSIXct objects can be very inconsistent, probably because the atomic constructor `.POSIXct()` is awful. The default tz when an object is built with `as.POSIXct()` is "", not `NULL` as with `Sys.time()`.

**Comment by moodymudskipper** [comment]
Thanks!

**Pull request merged**
